### ISSUE TITLE
Not possible to add members to teams

### ISSUE THREAD

**Issue by RachelMuston** [canada-ca/devex#10]
Seems to be the case even if logged in as admin or as the owner of that team (from the team page or the 'editing' team page).

![trying_to_add_team_members](https://user-images.githubusercontent.com/29108013/33246637-d7527fb0-d2e4-11e7-8a63-6641fa829050.png)

**Comment by markwooff** [comment]
Decided to leave the singular Team Member displayed but renamed as the Team Lead. Don't need to show more than this.
