### ISSUE TITLE
Replace 'Code With Us' with new name

### ISSUE THREAD

**Issue by markwooff** [canada-ca/devex#13]
For discussion, can replace links throughout site with new name & wiki link.

Can put Code With Us wiki content on this repo to have all info in one space.

**Comment by RachelMuston** [comment]
Done!  Wiki content moved to the devex repo.  Mentions of Code with Us removed from the dev exchange site.  Code with us repo can be deleted.

**Comment by markwooff** [comment]
@RachelMuston 10-4, our "Code With Us" fork has been deleted.
