### ISSUE TITLE
Add Google Analytics to website

### ISSUE THREAD

**Issue by markwooff** [canada-ca/devex#14]

**Comment by RachelMuston** [comment]
I've added this to the project kanban board.  @markwooff can I close this as an issue?

**Comment by markwooff** [comment]
Where is the kanban board located? If it's there then I imagine we can close issue here.

**Comment by markwooff** [comment]
Well actually, I can go in and GA right now if someone creates a new site within Google Analytics. I'd just need to log in to the account and grab the analytics script 👍
