### ISSUE TITLE
Programs/Teams - text changes and a bug?

### ISSUE THREAD

**Issue by RachelMuston** [canada-ca/devex#15]
When I click on Teams and choose to 'add a new team', the following screen uses the 'program' phrasing.  Should be changed to 'team'
![change_program_to_team](https://user-images.githubusercontent.com/29108013/33619337-f18f7598-d9b2-11e7-9b56-62bfdcb20155.PNG)

Also after successfully saving the team (called Rachels team) it does not show up in the Team list.  Bug?  @markwooff

**Comment by RachelMuston** [comment]
Above changes (Program to Team) to French page also pls. :)

**Comment by markwooff** [comment]
Issue has been fixed!
