### ISSUE TITLE
Changes to Project pages

### ISSUE THREAD

**Issue by RachelMuston** [canada-ca/devex#16]
To match the Team page, is it possible to change the 'add project' button as follows:

Currently:

![new_project](https://user-images.githubusercontent.com/29108013/33619684-ded04490-d9b3-11e7-9dd3-45e30ed4c865.PNG)

Change to:
'+ New Project'

Also, requesting a change to next screen to change 'program' to 'team'
![adding_new_project](https://user-images.githubusercontent.com/29108013/33619869-476aaa40-d9b4-11e7-9189-54f5580cbc52.PNG)

Changes to French pages too pls. :-)
@markwooff

**Comment by RachelMuston** [comment]
Also, same as with the team page...I can successfully add a project but it does not show up in the project list.  Bug?

**Comment by markwooff** [comment]
I've changed the label from Program to Team, but the other issue you're mentioning is due to the team/project not being published.

You can save these objects in the system, but you will have to go back to the list and hit the "Publish" button before they will be visible to all users:

![image](https://user-images.githubusercontent.com/5591488/33624114-4c324d28-d9c1-11e7-93bc-179375ec2a7d.png)

**Comment by RachelMuston** [comment]
Interesting....
When I am logged in as admin, I see this in the Team list:
![team_list_admin](https://user-images.githubusercontent.com/29108013/33624983-23e675ee-d9c4-11e7-8f50-53e40f8a7d51.PNG)

When I am logged in as myself, I see this in the Team list:
![teams_list_bug_testing](https://user-images.githubusercontent.com/29108013/33624945-0c11f704-d9c4-11e7-8787-2962c83f9dea.PNG)

This leads me to believe that the publish/unpublish functionality is only available to admin which I think is a problem.

But also, in either case, I do not see the Rachels team that I created.  And I know it exists because I can select this team when I am creating a project
![new_project_rachels_team](https://user-images.githubusercontent.com/29108013/33625024-4ac77ac8-d9c4-11e7-859a-c74f542e2f52.png)

??

**Comment by RachelMuston** [comment]
After further testing...
Seems that clicking away from the Team page (e.g. to opportunities or home) and back to the Team page is not enough to refresh the team list after adding a new team.  Neither is logging off and logging back on.  The only way to refresh the team list is by clicking Ctl+R or clicking the refresh button next to the page address.  Seems like this is a bug...suspect other users will not know to hard refresh the page.

**Comment by markwooff** [comment]
There is some logic behind how the publishing of Projects & Teams works... I agree that it might not make sense for one administrator user to have all the publishing rights but that's how the system works as-is.

The logic follows these rules:
- A new team can be created but needs to be published by an admin.
- A new project can be created but needs to be published by an admin.
-- An unpublished team will show up in the list when creating a new project, but the team will not be able to be published until that team is also published.
