### ISSUE TITLE
hard refresh required on all pages

### ISSUE THREAD

**Issue by RachelMuston** [canada-ca/devex#18]
this happens when:
-adding a team (after successfully adding a team, clicking on the team page or logging out and logging in will not show the team.  A hard refresh is required)
-to view the team details that have been added (after doing a hard refresh so that the team appears in the list, clicking on the team link will take you to the team page but not show all the team details.  A hard refresh is required here too).
-when adding a project (after successfully adding a project, clicking on the project page or logging out and logging in will not show the project.  A hard refresh is required).

**Comment by markwooff** [comment]
Can confirm that this happened on Internet Explorer, except a hard refresh wasn't required. A simple refresh was able to show the new data. Will need to look at the IE caching that is causing this issue.

**Comment by markwooff** [comment]
@RachelMuston looking into this today so we'll be good for tomorrow's walkthrough 👍

**Comment by markwooff** [comment]
Good news! This issue has been fixed, please test on your end before closing.
