### ISSUE TITLE
project publishing issue

### ISSUE THREAD

**Issue by RachelMuston** [canada-ca/devex#19]
Project shows as unplublished on the Team page (after a hard refresh) even though it shows as published on the project page.

**Project page:**
![rachels_project_published](https://user-images.githubusercontent.com/29108013/33724656-03cee43c-db3e-11e7-866f-865b5ca10c28.png)

**Team page (shows project as unpublished):**

![rachels_team_projects_list](https://user-images.githubusercontent.com/29108013/33724693-1e9c1a46-db3e-11e7-9075-31389487f50d.png)

**Comment by RachelMuston** [comment]
Weird.  Just switched to my macbook (using Chrome) and I'm not seeing 'unpublished' in the actions column.  But I am still seeing it on my work laptop (using IE).  A hard refresh on the work laptop doesn't fix it.  Browser issue?

**Comment by markwooff** [comment]
Right, this could be why I'm not seeing the issues. Also working in Chrome on a Macbook.

Wonder if the application is caching parts of the site on IE, will switch over to a PC to test.

**Comment by RachelMuston** [comment]
Confirmed!  I just did a test where i added teams and projects in Chrome - no issue.
Did the same in IE....needed to do the hard refresh.  

Do you see the same?

I think a lot of departments have not rolled out Chrome.  :-(  Fixable?

**Comment by markwooff** [comment]
Should be fixable, might need to make some tweaks to the cache so all works on IE. Testing that out now.

**Comment by markwooff** [comment]
Same as other issue, caching has been tweaked so that IE will display all changes without refreshing.
