### ISSUE TITLE
Change Program to Team in notification messages

### ISSUE THREAD

**Issue by RachelMuston** [canada-ca/devex#21]
Hey @markwooff , 
When I publish and unpublish a team I get the following messages:  (to change to 'Team' pls).  Note:  I'm adding these to my list of things to get translated. :)
![program_published_successfully](https://user-images.githubusercontent.com/29108013/33735194-9b857ff2-db5c-11e7-81c9-80e9d7700eef.png)

![program un-published successfully](https://user-images.githubusercontent.com/29108013/33735203-9e70359a-db5c-11e7-9ed4-b5f778910d66.png)

**Comment by markwooff** [comment]
This has been fixed. Thanks for finding these additional texts where translation is needed!
