### ISSUE TITLE
Choosing to add a project from the French Project screen flips to the english add project screen

### ISSUE THREAD

**Issue by RachelMuston** [canada-ca/devex#22]
When I am on the french project page and click on 'Lister un nouveau projet' I get flipped to the english add a new project screen

![new_project_switches_to_english](https://user-images.githubusercontent.com/29108013/33736033-312cc1ee-db5f-11e7-9444-ea101309f5a9.PNG)

I can then click on Francais to get to the french screen which works but the content is in English.

**Comment by RachelMuston** [comment]
Same thing happens from the French Team page (clicking on 'Nouvelle equipe' opens the english New Team page)

**Comment by RachelMuston** [comment]
Same thing on the French Opportunities page (clicking on 'Publier une possibilite' opens the english New Opportunity page)

**Comment by markwooff** [comment]
These are now all fixed!
