### ISSUE TITLE
Adjust formatting for 'reward amount' drop down in French New Opportunity page

### ISSUE THREAD

**Issue by RachelMuston** [canada-ca/devex#23]
Hey @markwooff can we adjust the formatting of this drop down on the french page?

![dollar formatting in french](https://user-images.githubusercontent.com/29108013/33736536-f0c99ddc-db60-11e7-9dff-9664b4604c78.png)

like this:  9 500,00 $ instead of $9,500.00

Actually, can we also get rid of the .00 in both the drop downs to make it easier to read?

**Comment by markwooff** [comment]
Managed to get rid of the decimal amount, will take a bit of work to get the French currency formatting in unfortunately. Looking into it!

**Comment by markwooff** [comment]
This has now been done too 👍  more learning!
