### ISSUE TITLE
Identifying mandatory fields

### ISSUE THREAD

**Issue by RachelMuston** [canada-ca/devex#25]
Short description is not identified as a mandatory field in the +new team and +new project pages however it is not possible to save a team or project without one.

One option would be to identify short description as all the other mandatory fields 
By putting "Short Description is required" underneath the field.

But an enhancement we might want to think about is just putting a "*" next to each field that is mandatory and then a note at the bottom of each page that says "* denotes a mandatory field"  Would be a lot cleaner.

**Comment by markwooff** [comment]
Agree that a standard notice for required fields would be the best solution. Assuming that an asterisk was supposed to be inside your quotes? Could have it appear as it does in WET:

![image](https://user-images.githubusercontent.com/5591488/33767608-58141bcc-dbf0-11e7-85e4-f3913f855079.png)

and in French:

![image](https://user-images.githubusercontent.com/5591488/33767615-61452a9c-dbf0-11e7-8435-1fd2ff4585da.png)

**Comment by RachelMuston** [comment]
That would be excellent.  Is it possible to do this on all the english and french pages before the webinar next week?  (yup - I had meant to put an asterisk inside those quotes!  Ooops!)

**Comment by markwooff** [comment]
No worries there, the required labels have all been added in! Looks like we'll need some translations for the labels on all the form items when creating new teams/projects/opportunities though.

**Comment by RachelMuston** [comment]
Looks awesome!!

Is it possible to remove all the grey text underneath the mandatory fields (e.g. 'Opportunity title is required')?

All good on the translations for the labels on those three pages...sent them off today.  :-)  Asked for them back by noon on Tuesday.

**Comment by markwooff** [comment]
Great! Love the proactive-ness here for translations!

Just removed those repetitive 'required' lines you mentioned as well.
