### ISSUE TITLE
Is it possible to make the department name show up in French on the French team page?

### ISSUE THREAD

**Issue by RachelMuston** [canada-ca/devex#27]
Hey @markwooff would it be possible to have the department names show up in french on the french team page?

Was thinking that could be done by making the department field a drop down list in the +new field page?

![department_possible_drop_down](https://user-images.githubusercontent.com/29108013/33782014-e0e06fbc-dc24-11e7-8ddb-ebe3b94c5081.PNG)

![departments_in_the_team_list](https://user-images.githubusercontent.com/29108013/33782017-e5df62f2-dc24-11e7-8a94-6e0f5bfbdf0d.PNG)

**Comment by markwooff** [comment]
It's possible, would just need some tweaks to the page. Wondering if I should use the same dropdown we use on the GCcollab register page here: https://gccollab.ca/register (select federal from the Occupation dropdown). Or did you want a limited list of Federal depts?

**Comment by RachelMuston** [comment]
Same dropdown as the one on GCCollab would be awesome.  :-)

**Comment by markwooff** [comment]
Done and done! Turns out translations in Angular has some very interesting syntax to have them show up properly in each language. Learning quite a few things on the go here 👍

**Comment by RachelMuston** [comment]
Yay for learning all the things!!!  Drop down works perfectly!
