### ISSUE TITLE
Can't seem to publish an opportunity

### ISSUE THREAD

**Issue by RachelMuston** [canada-ca/devex#29]
Unlike with Teams and Projects, with Opportunities, I don't seem to have the ability to publish.

I don't have a publish button on the opportunity list page, nor when I click on the specific opportunity, nor when I edit the opportunity. ??  Can only admin publish opportunities?

My team and my project are published....

![unpublished opportunity](https://user-images.githubusercontent.com/29108013/33833967-63afab3e-de4f-11e7-947e-d38b06d34b40.png)

![unpublished opportunity2](https://user-images.githubusercontent.com/29108013/33833975-6a563eda-de4f-11e7-8157-2907494cc6a1.png)

![no publish button](https://user-images.githubusercontent.com/29108013/33833984-7309c628-de4f-11e7-99cb-9002c55a9143.png)

**Comment by markwooff** [comment]
Your project "Sharing Public Opinion Research with Library and Archives Canada" doesn't appear to be published. Does it appear to be published on your end?

**Comment by RachelMuston** [comment]
You are right!  My bad.  Brings up another issue though which I'll post separately.
