### ISSUE TITLE
Unpublished notifier on the Projects page

### ISSUE THREAD

**Issue by RachelMuston** [canada-ca/devex#30]
When a Project is unpublished, there is no notifier saying so on the page that lists all the projects.

This is different from the Team and opportunity pages which says next to each line item if it is unpublished.

Possible to have the same usability on the Project page?

**Comment by markwooff** [comment]
Interesting.. I'm seeing the same UI for all 3 areas:

![image](https://user-images.githubusercontent.com/5591488/33836033-48b6989a-de56-11e7-92cc-0ab2464ed704.png)

Will take a look and make sure the "UNPUBLISHED" shows for non-admins.

**Comment by RachelMuston** [comment]
That would be awesome.  Yeah the 'Actions' column doesn't show up for me in the projects screen:

![no unpublished notifier](https://user-images.githubusercontent.com/29108013/33836242-e100b202-de56-11e7-86d7-49994d697334.png)

Related, in the other screens (Team and Opportunity), the Action column shows up but there is no column header...

![no action header2](https://user-images.githubusercontent.com/29108013/33836317-1179dada-de57-11e7-813d-a272af7065be.png)

**Comment by markwooff** [comment]
Hmm what browser are you using?

**Comment by markwooff** [comment]
Okay have a look when you get a chance, issue should now be fixed.
