### ISSUE TITLE
How to ensure we have bilingual content for each team, project and opportunity

### ISSUE THREAD

**Issue by RachelMuston** [canada-ca/devex#31]
Hey @markwooff ... something I've been thinking about as I've begun entering a more 'true to life' opportunity (and project and team)...
We will be requiring that all content put on GCDevExchange is bilingual.  I had thought, no big deal, we'll just get everyone to enter both the english and french in each field like this:
![bilingual team name](https://user-images.githubusercontent.com/29108013/33835962-15e353ea-de56-11e7-913b-e4a510d9accd.png)

And I think that could work for the Team and project pages. But it starts to get really messy in the Opportunity page...for the latest opportunity I have posted, if I include the french as well as the english in the opportunity title, description and project name, I think that table will become unreadable..

Any thoughts of what we could do?

**Comment by markwooff** [comment]
The best way to address this would be to have two separate input areas - one for English & one for French. Unfortunately this means duplicating each field in the frontend and in the database...

The team/project/opportunity information would be entered in both English & French, with only one being shown to the user based on which language they've selected. Wouldn't be a quick task but technically it can be done.

**Comment by RachelMuston** [comment]
Ok let’s hold on this for now.

**Comment by markwooff** [comment]
Duplicate issue as https://github.com/canada-ca/devex/issues/60, closing.
