### ISSUE TITLE
Replace any mentions of Code with Us with GCDevExchange

### ISSUE THREAD

**Issue by RachelMuston** [canada-ca/devex#34]
Any mentions of Code with us should be replaced with GCDevExchange.  Any links to the wiki on the Code with Us repo should be replaced with the link to the wiki on the devex repo: https://github.com/canada-ca/devex/wiki/1.-Introduction-%7C-Introduction 

E.g.  In the Add Opportunity page, the header should be changed:  replace Code with Us with GCDevExchange (CarrefourProgGC in french).
Also the Read the Guide button should link here:   https://github.com/canada-ca/devex/wiki/1.-Introduction-%7C-Introduction 

![add_opportunity_header](https://user-images.githubusercontent.com/29108013/33906103-dda655c8-df4e-11e7-8367-3fe2d396763e.PNG)

**Comment by RachelMuston** [comment]
Actually the text under the title should read:
By posting an opportunity on the GCDevExchange, you are agreeing to the following Terms.  Make sure you are familiar with the process and understand your responsibilities for managing an opportunity.

Also the link to the terms should go to here:
https://github.com/canada-ca/devex/blob/master/GCDevExchange_-_Terms_and_Conditions.pdf 

(I removed the BC terms and conditions from our repo - sorry, did this on prod without thinking!!)

**Comment by markwooff** [comment]
Text has all been changed! Have a look at the text when creating a new opportunity and let me know if we're good with that.

**Comment by RachelMuston** [comment]
All good except for one lingering 'code with us' mention.  (change to GCDevExchange)
![opportunity_header](https://user-images.githubusercontent.com/29108013/33955020-2d104c9a-e008-11e7-8679-2212465a96f0.PNG)

**Comment by markwooff** [comment]
Oops, must have missed that one. Fixed!

**Comment by RachelMuston** [comment]
OOoo just found this in another spot.  In each opportunity (not the +new opportunity), it has this near the top of the page:
![opportunity page header_not_the_edit_screen](https://user-images.githubusercontent.com/29108013/33958314-0e641268-e012-11e7-85ad-49b30905cfd9.PNG)

**Comment by markwooff** [comment]
Give the page a hard refresh, that should have been included in the last fix as well.
