### ISSUE TITLE
Some english where there should be french

### ISSUE THREAD

**Issue by RachelMuston** [canada-ca/devex#37]
Hi @markwooff  just found a couple of things...

When I click on a specific project the Edit button is in English: 
![individual_project_screen_french_edit_button](https://user-images.githubusercontent.com/29108013/33996269-b9827ada-e0ae-11e7-8058-6cff80adde85.PNG)

Helper text in grey on the new project screen (maybe just remove this text)
![new_project_french_screen](https://user-images.githubusercontent.com/29108013/33996290-c6892e4a-e0ae-11e7-9bc3-eeb4bb777ee8.PNG)

**Comment by markwooff** [comment]
Hmm I don't remember seeing the translations for "Edit" or "A short description of the project". Do you think you could provide a quick translation for that?

*Name = nom* so no worries there.
