### ISSUE TITLE
Link to repo from homepage

### ISSUE THREAD

**Issue by lchski** [canada-ca/devex#40]
Hia! Just a quick note that there’s no link to this repo anywhere on the site itself. I had to find the repo manually. Might be worth adding a link to it in the “Re-use this code” section on the homepage. (I’d submit a PR but am not sure about the translations/where to put the link.)

Great work!

**Comment by markwooff** [comment]
Great idea @lchski, will be committing some new code with a link to the repo in the **Re-use this code** section as well as the **Work With Us** link list at the bottom of the page.

**Comment by lchski** [comment]
Awesome, glad to hear it!

**Comment by markwooff** [comment]
Thanks for the suggestion! Live site is now up to date.
