### ISSUE TITLE
uploading content to dev server error message

### ISSUE THREAD

**Issue by RachelMuston** [canada-ca/devex#5]
![dev servererror](https://user-images.githubusercontent.com/29108013/32854903-1aa89aea-ca0e-11e7-84a1-f7b905115d2f.png)

Getting this error when we try to add user profile pics and also when we tried to replace the bcdevexchange logo.

When adding a logo, we get conflicting error messages - a success message and a fail message.  And then it automatically adds the bcdevexchange logo (when we tried to add a new team)

**Comment by RachelMuston** [comment]
This error also occurs on prod (for adding logos)

**Comment by markwooff** [comment]
Uploading profile/team images should now be working on both the live site & dev. Was able to change/upload images on my end but please give it a test when you have a chance.
