### ISSUE TITLE
Fix links to BC Ministry of Citizens

### ISSUE THREAD

**Issue by gabrielcossette** [canada-ca/devex#52]
There are references to BC Ministry of Citizens for the collection of personal information.

Here's a few examples: https://github.com/canada-ca/devex/search?utf8=✓&q=Ministry+of+Citizens&type=

This of course needs to be updated to point to GoC policy :)

Thanks Rob Johnston on GCconnex for pointing this out!

**Comment by RachelMuston** [comment]
Thanks @gabrielcossette! 

@markwooff here is the screen shot from user profile screen:
![collection_notice_user_profile_screen](https://user-images.githubusercontent.com/29108013/35595348-6836237e-05e4-11e8-9940-8b4c5eb68d44.PNG)

here is the english text to replace it:
This personal information is collected by the Government of Canada under s. 4 of the [Privacy Act](http://laws-lois.justice.gc.ca/eng/acts/p-21/page-1.html#h-5) for the purposes of communications with registered users.  Should you have any questions about the collection of this personal information please contact: [Consultations@pco-bcp.gc.ca](mailto:Consultations@pco-bcp.gc.ca) 

French text coming....

**Comment by markwooff** [comment]
@RachelMuston just let me know when the French is ready to go and I'll update both!

**Comment by RachelMuston** [comment]
@markwooff here is the French! :)
Ces informations personnelles sont recueillies par le gouvernement du Canada en vertu de l’article 4 de la [Loi sur la protection des renseignements personnels](http://laws-lois.justice.gc.ca/fra/lois/p-21/page-1.html) pour des  fins de communication auprès d’utilisateurs inscrits. Pour toute question concernant cette collecte de renseignements personnels, veuillez communiquer avec : [Consultations@pco-bcp.gc.ca](mailto:Consultations@pco-bcp.gc.ca)

**Comment by markwooff** [comment]
Great thanks @RachelMuston! The updated text is now live on the dev & prod sites. Closing issue.
