### ISSUE TITLE
add "Including taxes" to the opportunity page

### ISSUE THREAD

**Issue by RachelMuston** [canada-ca/devex#54]
Hey @markwooff when you get a sec, could you add the following text to the "Fixed Price" column header on the opportunity page:
English screen:   (incl. taxes)
Frrench screen:   (taxes incl.)

![including_taxes](https://user-images.githubusercontent.com/29108013/35742827-b9e7c9f8-0809-11e8-9aae-a290fa0691db.PNG)

also open to suggestions for how to include something to this effect on the individual opportunity screens

**Comment by markwooff** [comment]
I could include the same text in the green price label on the individual opportunity page:

![image](https://user-images.githubusercontent.com/5591488/35749162-af903124-081e-11e8-9a46-805f2c5476a3.png)

Thoughts?

**Comment by markwooff** [comment]
Also slight usability comment about updating the table header. If we include **(incl. taxes)** in the header, the table would squish down to this:

![image](https://user-images.githubusercontent.com/5591488/35749386-5f3a3174-081f-11e8-9bb0-a2169998b0d3.png)

How about on both the List and Individual page, we include the text after the price?

![image](https://user-images.githubusercontent.com/5591488/35749411-78564882-081f-11e8-838a-5d37f43c3190.png)

**Comment by RobJohnston** [comment]
You'd be either squishing it one way or the other.  Maybe it could be displayed better without the use of a table?

**Comment by markwooff** [comment]
Originally the layout was identical to the BCDevExchange (https://bcdevexchange.org/opportunities) however accessibility had to be kept in mind for the GC.

Once we separate the English & French titles/descriptions the table won't feel as large.

**Comment by RachelMuston** [comment]
Nice suggestion @markwooff !  I like option 2 (including the text in the green area) for both the main opportunity page and the individual opportunity pages.  Consistent.  I like it.

Re: squishing....do we have a timeline for separating out the english and french titles and descriptions?  (is that something that is waiting on the decision on the URL stuff).

**Comment by markwooff** [comment]
@RachelMuston done! New labels are live on the site now.

As for the language text splitting, yes & no. I could add this function as part of our next sprint but even if we have only French language appearing on the French domain, the GitHub login functionality still wouldn't work (as everything is right now). Just need a firm decision on which direction we'll go for EN/FR splitting 👍
