### ISSUE TITLE
OAuth issues

### ISSUE THREAD

**Issue by RachelMuston** [canada-ca/devex#6]
1.  Remove connection to markwooff's account as part of the Oauth process.

2.  Verify that the authorization is for github account and public data only (and not authorization to go into private repositories)

3.  Verify the Oauth page is also available in French - if not raise with Github?

From John O'Brien:  "it might be worth NOT tieing it directly to any existing github profile, and figuring out if there's a way to genericize the link between developer account and developer repo locations...(gitlab, bitbucket, ms vstudio, github etc...)

On the i8n front, we did just complete a internatlization contract with HackerRank, to have them give us a proper French version of the site...github might be interested.  "

**Comment by ToferC** [comment]
Could we link this into our new authentication app? Just a thought.

**Comment by RachelMuston** [comment]
If there is a way to authenticate outside of GitHub that could be cool.  I know the bc dev exchange is looking to add authentication via LinkedIn as well (for govt mgrs that might not have GitHub accounts).  Would also be useful down the road for projects that reside on non-GitHub but still open source repos.  That being said, if it is a lot of work, it might be something to add to our gcdevex release 2 vs working on right now.

**Comment by markwooff** [comment]
@ToferC I think it would be awesome if we could tie in our Single Sign-On with GCDevEx or any other OAuth authentication. It will take some more time investment but will see how do-able it is.

May be good to look at for release 2 as you've mentioned @RachelMuston

**Comment by markwooff** [comment]
Good news, I've switched everything the GitHub application from my account to the new `GCDevExchange-CarrefourProgGC` account. Will now see this when signing up to GCDevEx:

![image](https://user-images.githubusercontent.com/5591488/33496401-0e98fcf4-d698-11e7-8eca-73c7ddc2f616.png)

**Comment by RachelMuston** [comment]
Looks awesome!  Will test this and let you know how it goes.

**Comment by markwooff** [comment]
We can’t always replace the default logo when we have a set logo for the GCDevExchange (or perhaps standard Canada.ca maple leaf logo).

**Comment by RachelMuston** [comment]
LOL.  I literally just changed the default logo to the canada.ca maple leaf logo.  :)

**Comment by RachelMuston** [comment]
Interesting @markwooff Now that I've changed the logo, when I test the registration, I get this:

The logo at the top is correct but then it has my donkey logo as well. Is that right?
![oauth_screenshot](https://user-images.githubusercontent.com/29108013/33555623-19f4dff8-d8cf-11e7-8f16-44d80fb106b6.png)

**Comment by markwooff** [comment]
It appears that the GitHub application account (GCDevExchange-CarrefourProgGC) icon appears at the very top of the page and the info related to the user's account will appear in the box:

![image](https://user-images.githubusercontent.com/5591488/33556311-6db80118-d8d1-11e7-995f-183af2a20167.png)

I think this is just how the OAuth is displayed for GitHub, the applications use the correct icon when looking at my GitHub application settings:

![image](https://user-images.githubusercontent.com/5591488/33556355-9da9534a-d8d1-11e7-957b-ef9867c8b6ee.png)

**Comment by RachelMuston** [comment]
Ok sounds good.  @markwooff I'm thinking we can close this issue? Or is anything outstanding?

**Comment by markwooff** [comment]
Nope we can close issue. Later on we can try implementing other authentication sources besides GitHub but that would be a separate issue.
