### ISSUE TITLE
opportunities page goes to a template

### ISSUE THREAD

**Issue by RachelMuston** [canada-ca/devex#66]
Hi @markwooff, I just got an email from a user who somehow ended up on this page:
https://beta.gcdevexchange.org/opportunities which goes to a template page instead of the real opportunities page (https://beta.gcdevexchange.org/en/opportunities).  Also if you click on 'opportunities' from this page it takes you to this page:
https://beta.gcdevexchange.org/opportunities/opportunities (which is also wrong).

Odd!

**Comment by RachelMuston** [comment]
Been playing around and it seems I can put anything in the middle (after .org and before the page name) and it will work but goes to a strange template page that is half right and half wrong - the main content is there but the headers and footers are all from a template.

E.g. I tested this:  https://beta.gcdevexchange.org/Sparkles&Unicorns/teams   :-)

**Comment by RachelMuston** [comment]
Figured out how the user ended up on that page - its the link from the main page that is pointing to the wrong link.  Same with french.

![broken_opportunities_link](https://user-images.githubusercontent.com/29108013/37117168-71e836ae-221e-11e8-80b4-6aef6151bea8.PNG)

**Comment by markwooff** [comment]
Will look into this! Thanks for flagging it.

**Comment by markwooff** [comment]
Links should now be fixed on prod :)
