### ISSUE TITLE
English dates in french opportunity posters

### ISSUE THREAD

**Issue by RachelMuston** [canada-ca/devex#70]
Hey @markwooff. Noticed this today when I toggled to French on an opportunity page:
![french_opportunity_page_dates](https://user-images.githubusercontent.com/29108013/37487842-2f3f4ac6-2869-11e8-8713-d83a0964dc35.PNG)

Is there a way for the dates to be in french format?  E.g. le lundi 22 janvier 2018

**Comment by markwooff** [comment]
These dates will now appear in French formatting on the FR pages!
