### ISSUE TITLE
Access to Apply to Opportunities

### ISSUE THREAD

**Issue by MaryBethBaker** [canada-ca/devex#73]
Hi @markwooff,

I tested the Dev site as a regular user; and the apply button never appears. I was trying to apply for the Decrease the supply of M&M's opportunity, but couldn't find the button.

Mary Beth

**Comment by markwooff** [comment]
Looking into this ASAP, thanks for flagging @MaryBethBaker

**Comment by markwooff** [comment]
This should now be fixed, could you please confirm @MaryBethBaker ?

**Comment by MaryBethBaker** [comment]
Nope - still sending me back to the dev homepage and not signing me into the system.

Mary Beth

**Comment by markwooff** [comment]
Okay so this is an IE issue then, not that the button isn’t working. Will take a look into this.

**Comment by markwooff** [comment]
Closing as the discussed issue is actually https://github.com/canada-ca/devex/issues/75
