### ISSUE TITLE
places with mentions of BCDevExchange - should be changed to GCDevExchange

### ISSUE THREAD

**Issue by RachelMuston** [canada-ca/devex#9]
User registration page:
![errormessagesdevex](https://user-images.githubusercontent.com/29108013/33246563-0f99607e-d2e4-11e7-8a23-05d410ef0d30.png)

**Comment by RachelMuston** [comment]
Also the default team logo is the bcdevexchange logo.  
![bcdevexchange_logo](https://user-images.githubusercontent.com/29108013/33246669-31b360d2-d2e5-11e7-88f7-c58620f3c352.png)

Since there is no GCDevExchange logo, can we use this instead:

![canada_image](https://user-images.githubusercontent.com/29108013/33246664-1730bf8e-d2e5-11e7-9087-c34004876a20.png)

**Comment by markwooff** [comment]
These updates have been made and are up on the dev site at https://dev.gcdevexchange.org/ - we can review all changes here before pushing up to the live site. Thanks!

**Comment by RachelMuston** [comment]
Hey @markwooff , I realized we forgot to put this one in issues:
![bc_text_in_profile_page](https://user-images.githubusercontent.com/29108013/33555794-a6f59186-d8cf-11e7-9465-642fb9eee1a4.png)

Change "BC public sector employee" to "Government of Canada employee" and "BCDevExchange" to "GCDevExchange"

**Comment by markwooff** [comment]
Hi @RachelMuston - just updated the dev site to include this change. Thanks
